# On-Call Schedule Configuration

team:
  - Alice
  - Bob
  - Charlie
  - Diana
  - Ethan
  - Fiona
  - George
  - Hannah
  - Ian
  - Julia
  - Kevin
  - Laura

schedule:
  start_date: "2025-11-03"  # First Monday
  num_blocks: 2              # Number of scheduling blocks
  weeks_per_block: 12        # Weeks per block
  timezone: "UTC"            # Timezone for schedule times

roles:
  D:
    name: "Day Shift"
    schedule:
      - days: [Mon, Tue, Wed, Thu, Fri]
        start_time: "09:00"
        end_time: "17:00"
  
  NP:
    name: "Night Primary"
    schedule:
      - days: [Mon, Tue, Wed, Thu]  # Weeknight shifts
        start_time: "17:00"
        end_time: "09:00"  # next day
      - days: [Fri]  # Weekend shift
        start_time: "17:00"
        end_time: "09:00"  # Monday morning
        span_days: 3  # Fri 17:00 -> Mon 09:00
  
  NS:
    name: "Night Secondary"
    schedule:
      - days: [Mon, Tue, Wed, Thu]  # Weeknight shifts
        start_time: "17:00"
        end_time: "09:00"  # next day
      - days: [Fri]  # Weekend shift
        start_time: "17:00"
        end_time: "09:00"  # Monday morning
        span_days: 3  # Fri 17:00 -> Mon 09:00

constraints:
  max_shifts_per_engineer: 3
  max_weekends_per_engineer: 1
  weekend_role: NP  # Which role includes weekend coverage

rules:
  roster_completeness: true       # C1: Each role filled exactly once per week
  no_consecutive_weeks: true      # C2: No back-to-back weeks
  max_workload: true              # C3: Limit total shifts per engineer
  weekend_limit: true             # C4: Limit weekend shifts per engineer
  role_separation: true           # C5: One role per person per week
  availability: true              # C6: Respect unavailability

solver:
  timeout_seconds: 60  # Maximum time for solver

files:
  availability_csv: "availability.csv"
  export_formats:
    - csv
    - ical
